# Generated by Django 3.1.5 on 2021-01-28 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='created_date',
            new_name='created',
        ),
    ]
